### ISSUE TITLE
How to use Butterworth filter in my app?

### ISSUE THREAD

**Issue by tunakif** [crotwell/OregonDSP-kotlin#1]
May I know how do I create and use Butterworth filter using your GitHub library? I'm so confused.

**Comment by crotwell** [comment]
In Java, Kotlin or javascript?
Here is a java example...
https://github.com/crotwell/sod/blob/sod4.0/src/test/java/edu/sc/seis/sod/process/waveform/OregonDSPFilterTest.java

**Comment by tunakif** [comment]
Java or Kotlin doesn't matter, both are almost the same. Thanks a lot! But you are using the original OregonDSP library there, right? How about if I want to use your library?

**Comment by crotwell** [comment]
Should be very similar, as I tried to do the port with minimal changes.
